mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
curr_dir := $(notdir $(patsubst %/,%,$(dir $(mkfile_path))))

ifdef DEBUG
	CFLAGS += -g
endif

# Path to cUnit module
CUNIT_PATH := /home/phantom/CP_Systems/Implementations/cUnit
CUNIT_LIB_PATH := $(CUNIT_PATH)/bin/linux-x86_64/lib_cunit
CUNIT_INCLUDE := $(CUNIT_PATH)/include

# Include directory
TESTS_INCLUDES := $(curr_dir)/include

# Add macro definitions
CFLAGS += -DTESTING
CFLAGS += -DNATIVE
# Add cUnit framework
CFLAGS += -I$(CUNIT_INCLUDE)
CFLAGS += -I$(TESTS_INCLUDES)

include $(curr_dir)/tests-ipc-queues/Makefile.linux
include $(curr_dir)/tests-utils/Makefile.linux
include $(curr_dir)/tests-mac/Makefile.linux

LDFLAGS += $(CUNIT_LIB_PATH)
LIBS += ipcqueuesT
LIBS += utilsT
LIBS += mclmacT
LIBS += cunit
