mkfil_path := $(abspath $(lastword $(MAKEFILE_LIST)))
curr_dir_utils := $(notdir $(patsubst %/,%,$(dir $(mkfil_path))))

SRC_DIR := $(curr_dir)/$(curr_dir_utils)
OBJ_DIR_U := $(BIN)/tests-utils
LIB := $(BIN)/lib

OBJSA = utils_tests.o timeouts_test.o
OBJS = $(addprefix $(OBJ_DIR_U)/, $(OBJSA))

TARGETS += utils_obj_dir $(LIB)/libutilsT

all : $(TARGETS)

utils_obj_dir :
	mkdir -p $(OBJ_DIR_U)

$(LIB)/libutilsT: $(OBJS)
	$(AR) $@.a $^
	$(RL) $@.a

$(OBJ_DIR_U)/%.o: $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

$(OBJ_DIR_U)/%.o: $(TESTS_INCLUDES)/%.h
